# Test1:
## Initialize an NxN matrix

In [7]:
n = 5
board = zeros(Int8, n+2, n+2)
A = zeros(Int8, n+2, n+2)
board[3,2] = 1
board[3,3] = 1
board[3,4] = 1
for i in 2:n+1
    for j in 2:n+1
        A[i,j] = board[i+1,j] + board[i+1,j+1] + board[i,j+1] + board[i-1,j] + board[i-1,j-1] + board[i,j-1] + board[i+1,j-1] + board[i-1,j+1]
    end
end
board

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  1  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

## define a logic function

In [3]:
function livesOrDies(alive, liveNeighbors)
    if alive == 1
        if ((liveNeighbors > 3) | (liveNeighbors < 2))
            return 0
        end
    elseif liveNeighbors == 3
        return 1
    end
    return alive
end

livesOrDies (generic function with 1 method)

## start the game with an infinite loop

In [8]:
#while true
for n in 1:6
    for i in 2:n+1
        for j in 2:n+1
            A[i,j] = board[i+1,j] + board[i+1,j+1] + board[i,j+1] + board[i-1,j] + board[i-1,j-1] + board[i,j-1] + board[i+1,j-1] + board[i-1,j+1]
        end
    end
    for i in 2:n+1
        for j in 2:n+1
            board[i,j] = livesOrDies(board[i,j], A[i,j])
        end
    end
    #clear
    display(board)
end

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  1  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  1  0  0  0  0
 0  0  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  1  1  0  0  0
 0  0  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  1  1  0  0  0
 0  0  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

7×7 Matrix{Int8}:
 0  0  0  0  0  0  0
 0  0  1  1  0  0  0
 0  0  1  1  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0
 0  0  0  0  0  0  0

LoadError: BoundsError: attempt to access 7×7 Matrix{Int8} at index [3, 8]